/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

/**
 *
 * @author Jonathan Viera
 */
public class BarraArriba extends javax.swing.JPanel{

    /**
     * Creates new form BarraArriba
     */
    
    private JFrame ventana;
    
    public BarraArriba() {
        initComponents();
        panelEkis.setBackground(new Color(255,102,0));
        panelMin.setBackground(new Color(255,102,0));
        lblMin.setBackground(Color.LIGHT_GRAY);
        lblX.setBackground(Color.LIGHT_GRAY);
        
        panelEkis.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelEkis.setBackground(Color.RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelEkis.setBackground(new Color(255,102,0));
            }
        });
        lblX.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelEkis.setBackground(Color.RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelEkis.setBackground(new Color(255,102,0));
            }
        });
        
        panelMin.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelMin.setBackground(new Color(255,143,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelMin.setBackground(new Color(255,102,0));
            }
        });
        lblMin.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelMin.setBackground(new Color(255,143,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelMin.setBackground(new Color(255,102,0));
            }
        });
    }//Constructor
    
    
    public BarraArriba(JFrame parentFrame) {
        this.ventana = parentFrame;  // Asignar el JFrame recibido
        initComponents();
    }

    public void setParentFrame(JFrame parentFrame) {
        this.ventana = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        panelEkis = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        panelMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setPreferredSize(new java.awt.Dimension(1366, 40));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 41));
        jPanel1.setLayout(null);

        lblX.setBackground(new java.awt.Color(51, 255, 102));
        lblX.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        lblX.setText("X");
        lblX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblX.setFocusTraversalPolicyProvider(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEkisLayout = new javax.swing.GroupLayout(panelEkis);
        panelEkis.setLayout(panelEkisLayout);
        panelEkisLayout.setHorizontalGroup(
            panelEkisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(panelEkisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEkisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblX)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelEkisLayout.setVerticalGroup(
            panelEkisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(panelEkisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEkisLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblX)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(panelEkis);
        panelEkis.setBounds(1330, 0, 40, 50);

        lblMin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        lblMin.setText("-");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMinLayout = new javax.swing.GroupLayout(panelMin);
        panelMin.setLayout(panelMinLayout);
        panelMinLayout.setHorizontalGroup(
            panelMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(panelMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblMin)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelMinLayout.setVerticalGroup(
            panelMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(panelMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMinLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblMin)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(panelMin);
        panelMin.setBounds(1290, -20, 40, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        if (ventana != null) {
            ventana.dispose();  // Cerrar el JFrame si se ha establecido
        }
    }//GEN-LAST:event_lblXMouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        if (ventana != null) {
            ventana.setState(JFrame.ICONIFIED);  // Minimizar el JFrame si se ha establecido
        }
    }//GEN-LAST:event_lblMinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel panelEkis;
    private javax.swing.JPanel panelMin;
    // End of variables declaration//GEN-END:variables

    
}
