/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;

/**
 *
 * @author Jonathan Viera
 */
public class BarraArriba extends javax.swing.JPanel{

    /**
     * Creates new form BarraArriba
     */
    
    private JFrame ventana;
    
    public BarraArriba() {
        initComponents();
        panelEkis.setBackground(new Color(255,102,0));
        panelMin.setBackground(new Color(255,102,0));
        lblMin.setBackground(Color.LIGHT_GRAY);
        lblX.setBackground(Color.LIGHT_GRAY);
        
        panelEkis.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelEkis.setBackground(Color.RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelEkis.setBackground(new Color(255,102,0));
            }
        });
        lblX.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelEkis.setBackground(Color.RED);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelEkis.setBackground(new Color(255,102,0));
            }
        });
        
        panelMin.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelMin.setBackground(new Color(255,143,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelMin.setBackground(new Color(255,102,0));
            }
        });
        lblMin.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                panelMin.setBackground(new Color(255,143,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panelMin.setBackground(new Color(255,102,0));
            }
        });
    }//Constructor
    
    
    public BarraArriba(JFrame parentFrame) {
        this.ventana = parentFrame;  // Asignar el JFrame recibido
        initComponents();
    }

    public void setParentFrame(JFrame parentFrame) {
        this.ventana = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnMax = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setMaximumSize(new java.awt.Dimension(32767, 20));
        setPreferredSize(new java.awt.Dimension(1366, 20));

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));

        btnMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn Green.png"))); // NOI18N

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn Ama.png"))); // NOI18N

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button red.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel5.setText("ActivaTec");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose)
                .addGap(18, 18, 18)
                .addComponent(btnMin)
                .addGap(18, 18, 18)
                .addComponent(btnMax)
                .addGap(514, 514, 514)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnClose)
                .addComponent(btnMin)
                .addComponent(btnMax))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMax;
    private javax.swing.JLabel btnMin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
}
