/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;

/**
 *
 * @author Danie
 */
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Danie
 */
public class Carrusel extends javax.swing.JFrame {
private int currentImageIndex = 0;
    private BufferedImage[] images;
    private boolean running = true;
   
    
    /**
     * Creates new form Carrusel
     */
    public Carrusel() {
        initComponents();
        loadImages();     
        startCarousel();
    }
   private void loadImages() {
        String[] imagePaths = {"/images/TEC.jpg", "/images/partido.jpg", "/images/EvaluacionDocente.jpg", "/images/tigrestec.jpg"};
        images = new BufferedImage[imagePaths.length];
        for (int i = 0; i < imagePaths.length; i++) {
            try (InputStream is = getClass().getResourceAsStream(imagePaths[i])) {
                if (is != null) {
                    images[i] = ImageIO.read(is);
                } else {
                    System.out.println("No se encontró el archivo: " + imagePaths[i]);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
      private void startCarousel() {
        CarouselRunnable carouselRunnable = new CarouselRunnable();
        Thread carouselThread = new Thread(carouselRunnable);
        carouselThread.start();
    }

    // Cambiar a la imagen anterior
    private void previousImage() {
        currentImageIndex = (currentImageIndex - 1 + images.length) % images.length;
        updateImage();
    }

    // Cambiar a la siguiente imagen
    private void nextImage() {
        currentImageIndex = (currentImageIndex + 1) % images.length;
        updateImage();
    }

    // Actualizar el JLabel con la imagen actual
    private void updateImage() {
        if (images.length > 0) {
            imageLabel.setIcon(new ImageIcon(images[currentImageIndex]));
        }
    }
    private class CarouselRunnable implements Runnable {
        @Override
        public void run() {
            while (running) {  // El hilo se ejecuta continuamente
                try {
                    SwingUtilities.invokeLater(() -> nextImage()); // Cambiar a la siguiente imagen en el Event Dispatch Thread
                    Thread.sleep(5000); // Espera de 5 segundos entre cambios
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt(); // Restaurar el estado de interrupción
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        imageLabel.setPreferredSize(new java.awt.Dimension(911, 377));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
